services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: memories_user
      POSTGRES_PASSWORD: memories_pass
      POSTGRES_DB: memories_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
